spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyolle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: studyolle
    password: studyolle
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    reids:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
