spring:
  jpa:
    properties:
      hibernate:
        format_sql: true     # SQL 보기 좋게 포맷

  mvc:
    hiddenmethod:
      filter:
        enabled: true  # HTML <FORM>에서 th:method에서 PUT 또는 DELETE를 사용해서 보내는 _method를 사용해서  @PutMapping과 @DeleteMapping으로 요청을 맵핑.

  mail:
    host: smtp.gmail.com
    port: 587
    username: lhr5767@gmail.com
    password: jlycpgugwqusyhlj
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG           # 실행 SQL 로그
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # 바인딩 파라미터 로그



server:
  tomcat:
    max-http-form-post-size: 5MB