spring:
  datasource:
    url: jdbc:mysql://mysql:3306/studyolle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: studyolle
    password: studyolle
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    reids:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

app:
  host: https://mydomain.com #TODO 실제 도메인 적용후 nginx 설정 파일도 수정해야함..